/** wire 协议类型：单一事实源在 server/wire.ts，此处仅类型再导出（构建期擦除） */
export type {
	AuthorScript,
	ClientFrame,
	ConversationMode,
	DraftView,
	RpPanel,
	ServerFrame,
	UpdateWire,
	WireActivity,
	WireChannel,
	WireCheckpoint,
	WireChatInfo,
	WireChoice,
	WireMsg,
	WireSessionInfo,
	WireStats,
	WireStoryFile,
	WireSwipe,
	WorldState,
} from "../../server/wire.ts";
